version: "3.9"

services:
  apb-bot:
    build: .
    container_name: apb-fight-club-bot
    environment:
      TELEGRAM_TOKEN_FILE: /run/secrets/telegram_token
    volumes:
      - ./telegram_token.txt:/run/secrets/telegram_token:ro
      - ./data:/app/data
    restart: unless-stopped
